INSERT INTO GUESTS (NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Janet', 'Janet@insignia.com', 'Ireland', '45  Parkway', 'VIC', '12345');
INSERT INTO GUESTS (NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Victor', 'vic@insignia.com', 'Ukraine', '54  Center', 'NSW', '6543');
INSERT INTO GUESTS (NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Kimberly', 'kim@gmail.com', 'Brazil', '33 Plaza', 'QLD', '8745322');
INSERT INTO GUESTS (NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Joan', 'joan@mail.com', 'Moldova', '55 Dawn ', 'NSW', '54677894');
INSERT INTO GUESTS (NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Judith', 'Judith1@hotmail.com', 'United States', '2 Rose', 'NSW', '8987654');

INSERT INTO ALLERGIES (GUEST_ID, NAME) VALUES ((SELECT GUEST_ID FROM GUESTS WHERE NAME = 'Victor'), 'peanuts');
INSERT INTO ALLERGIES (GUEST_ID, NAME) VALUES ((SELECT GUEST_ID FROM GUESTS WHERE NAME = 'Victor'), 'milk');
INSERT INTO ALLERGIES (GUEST_ID, NAME) VALUES ((SELECT GUEST_ID FROM GUESTS WHERE NAME = 'Joan'), 'peanuts');
INSERT INTO ALLERGIES (GUEST_ID, NAME) VALUES ((SELECT GUEST_ID FROM GUESTS WHERE NAME = 'Judith'), 'eggs');

