CREATE TABLE GUESTS(
  GUEST_ID BIGINT PRIMARY KEY auto_increment,
  NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(32),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24)
);

CREATE TABLE ALLERGIES(
  ALLERGIE_ID BIGINT PRIMARY KEY auto_increment,
  NAME VARCHAR(16) NOT NULL,
  GUEST_ID BIGINT NOT NULL
);

ALTER TABLE ALLERGIES ADD FOREIGN KEY (GUEST_ID) REFERENCES GUESTS(GUEST_ID);

